export { default as viaCepApi } from "./viaCepApi";
export { default as ViaCepService } from "./ViaCepService";
export { default as senaiApi } from "./senaiApi";
export { default as senaiApiService } from "./senaiApiService";
export { default as validarUser } from "./validarUserService";
export { default as devicesService } from "./devicesService";
export { default as localsService } from "./localsService";
export { default as weatherApi } from "./weatherApi";
export { default as weatherService } from "./weatherService";
